---
name: Retriever for RPAN
version: 0.1.1
client_id: ohXpoqrZYub1kg
redirect_uri: http://localhost:65010/callback
user_agent: Retriever for RPAN (by u/mingoXII)
subreddits:
  - thegamerlounge
  - distantsocializing
  - theyoushow
  - redditsessions
  - theartiststudio
  - whereintheworld
  - glamourschool
  - animalsonreddit
  - redditmasterclasses
  - talentshow
  - redditinthekitchen
  - pan
